name: codespell
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  codespell:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Codespell
        run: make codespell
      - run: make check-clean-work-tree
